### PR TITLE
Remove unused iferr dependency

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by targos** [comment]
Ping @iarna?

**Comment by targos** [comment]
@iarna @zkat this is one dependency less in the npm tree ;)

**Comment by targos** [comment]
Anyone here?

**Comment by iarna** [comment]
It doesn't reduce the # of deps in npm, 'cause we use iferr all over the place, but yeah, no reason to have a dep we don't use.

**Comment by targos** [comment]
> we use iferr all over the place,

Sure, but this one was an old version that couldn't be deduped (I found it because it was nested in `node_modules/npm-concurrently/node_modules`)

**Pull request merged**
